### ISSUE TITLE
multiple http commands in a serie

### ISSUE THREAD

**Issue by LucLisette** [Supereg/homebridge-http-switch#1]
Hello,

I use "homebridge http switch" from @supereg. It works fine but I would like to use it to go to a sequence of urls. Now I can use it with Siri to close my blinds one at the time. Is it possible to close two or more blinds or.... with only one serie of http commands.
Sorry for my bad english. Also I'm new with almost no knowledge of programming.

An other solution would be fine also.

Regards,

Luc

**Comment by Supereg** [comment]
First of all, you could possibly create multiple switches and combine them with a scene to control them all at wants.

However your idea is worth thinking about. You mean that you can define multiple urls for on, off and status functionality? I will think about it considering scenarios like when one of many http requests fail and how to handle the switch state with multiple urls.

**Comment by LucLisette** [comment]
Andy,

Creating a scene has to be made on my iphone. 
I like it more when it is integrated in my raspberry ’s program.
Playing around with settings has as result that I have to reorganize my iphone with scenes every time.
If it was integrated in your packages it would be more easy.
I use your package as stateless switch just to trigger (0,2s) a blind via http.

Could you also give me some advice installing homebridge-gpio-wpi2.
I just restarted installing a second raspberry 3 from zero.
Every time I get to installing your package I’m in trouble with installing node-wiring-pi???

When I run homebridge after installing it, it runs fine. QR code and code are present.
Then I try to install your package and it goes wrong. I dont know the sequence of installing things that are needed.

On one raspberry it works just fine but I dont know what I did and in what order.

Thank you for your reply,

Regards

Luc

**Comment by Supereg** [comment]
Implementing multiple url support for stateless switch only could be easily possible, wouldn't collide with anything 🤔 I try my best to implement this in the next days.

I don't know what's going wrong with your configuration, since my switch is a very simple home bridge module I can't imagine this has to do something with my package specifically. It seems I'm probably also the wrong guy to give you support for this problem.

Regards Andi

**Comment by LucLisette** [comment]
Andi

I love to hear from you if you manage to implement multiple url.
Thank you for helping me. 

Regards

Luc

**Comment by LucLisette** [comment]
Andi,

Perhaps you forget about me.
I don’t want to put any pressure on you, but do you think you can implement multiple url?
Commanding more blinds at onces would be nice.
If you can’t do it then I have to find another way. It’s just that I like your approach.
I hope my way of writing isn’ t impolite.
Sorry, my english is terrible but I hope you understand.

Regards

Luc

**Comment by Supereg** [comment]
Hey,
please excuse the big delay. I still consider to implement the multiple url feature. Unfortunately I had to finish some other work the last week. I try my best to get it ready by the end of this week.

Greets Andi

**Comment by Supereg** [comment]
Refer to the README for configuration

**Comment by LucLisette** [comment]
Hello Andi

Thanks you for making this multiple url.
I tried it but I can’t figure out what goes wrong.

Below you can see a part of my working stateless blinds json file, and at the end the not working multiple json file.
Can you see what I do wrong?


Greets

Luc


This system version works for all my (8) blinds.

{
	"bridge": {
		"name": "Domotica L&L",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"accessories": [{
			"accessory": "HTTP-SWITCH",
			"name": "Open het linker raam",

			"switchType": "stateless",

			"onUrl": "http://192.168.1.7/command?XC_USER=luc.vorstenbos@skynet.be&XC_PASS=LLLLLLLLLL&XC_FNC=doAction&id=04/switch1On"

		},{
			"accessory": "HTTP-SWITCH",
			"name": "Sluit het linker raam",

			"switchType": "stateless",

			"onUrl": "http://192.168.1.7/command?XC_USER=luc.vorstenbos@skynet.be&XC_PASS=LLLLLLLLLL&XC_FNC=doAction&id=03/switch2On"

		}

	],
	"platforms": [

	]
}


This does not work. I tried with 3 blinds




{
	"bridge": {
		"name": "Domotica L&L",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"accessories": [{
		"accessory": "HTTP-SWITCH",
		"name": "Keuken",

		"switchType": "stateless",
		"onUrl": [
			"http://192.168.1.7/command?XC_USER=luc.vorstenbos@skynet.be&XC_PASS=LLLLLLLLLL&XC_FNC=doAction&id=04/switch1On",
			"http://192.168.1.7/command?XC_USER=luc.vorstenbos@skynet.be&XC_PASS=LLLLLLLLLL&XC_FNC=doAction&id=03/switch2On",
			"http://192.168.1.7/command?XC_USER=luc.vorstenbos@skynet.be&XC_PASS=LLLLLLLLLL&XC_FNC=doAction&id=01/switch3On"
		]
	}],

	"platforms": [

	]
}

**Comment by LucLisette** [comment]
Sorry Andi,

I did send the wrong file.

This one is correct.

Regards

Luc

This json file version works fine for all my (8) blinds seperately:

{
	"bridge": {
		"name": "Domotica L&L",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"accessories": [{
			"accessory": "HTTP-SWITCH",
			"name": "Open het linker raam",

			"switchType": "stateless",

			"onUrl": "http://192.168.1.7/command?XC_USER=luc.vorstenbos@skynet.be&XC_PASS=LLLLLLLLLL&XC_FNC=doAction&id=04/switchOn"

		},{
			"accessory": "HTTP-SWITCH",
			"name": "Sluit het linker raam",

			"switchType": "stateless",

			"onUrl": "http://192.168.1.7/command?XC_USER=luc.vorstenbos@skynet.be&XC_PASS=LLLLLLLLLL&XC_FNC=doAction&id=03/switchOn"

		}

	],
	"platforms": [

	]
}


This json file does not work. I tried it with 3 blinds and don’t know what i do wrong.
I did it with and without /api/ in the url.




{
	"bridge": {
		"name": "Domotica L&L",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"accessories": [{
		"accessory": "HTTP-SWITCH",
		"name": "Keuken",

		"switchType": "stateless",
		"onUrl": [
			"http://192.168.1.7/command?XC_USER=luc.vorstenbos@skynet.be&XC_PASS=LLLLLLLLLL&XC_FNC=doAction&id=04/switch1On",
			"http://192.168.1.7/command?XC_USER=luc.vorstenbos@skynet.be&XC_PASS=LLLLLLLLLL&XC_FNC=doAction&id=03/switch2On",
			"http://192.168.1.7/command?XC_USER=luc.vorstenbos@skynet.be&XC_PASS=LLLLLLLLLL&XC_FNC=doAction&id=01/switch3On"
		]
	}],

	"platforms": [

	]
}

**Comment by Supereg** [comment]
I tested It on my homebridge instance. Configuration ist correct. Json Syntax is correct. The switch handles the array correctly.
This probably isn't a problem with my piece of code. Did you enter the correct urls for your http device? The "/switch#On" at the end seems like copied from my example urls and most likely not like the syntax your http server is expecting 🤔

**Comment by LucLisette** [comment]
Andi,

Yes the /switch#on is copied from your example. The url's are correct because they work in the other configuration.
What should I do with the /switch#on? I think its just a sequence of numbers like, switch1on, switch2on.......indicating the next coming url?
What is the meaning of that number?
Sorry to bother you all the time.

Regards,

Luc

**Comment by Supereg** [comment]
The whole url (like "http://localhost/api/switch1On") was made as an example url and should be completely replaced with your own, custom url. Whatever your url is, completely delete my example and enter your own one.

**Comment by LucLisette** [comment]
Sorry to trouble you Andi,

Please try to explain it one ’s more. Its very clear to me that you made no mistake. I just don ’t understand what to do.

When I use a single stateless command, as it was like before this is what I used as url:
			http://192.168.1.7/command?XC_USER=luc.vorstenbos@skynet.be&XC_PASS=LLLLLLLLLL&XC_FNC=doAction&id=04/switchOn <http://192.168.1.7/command?XC_USER=luc.vorstenbos@skynet.be&XC_PASS=LLLLLLLLLL&XC_FNC=doAction&id=04/switchOn>
	At the end just”/switchon" with no number and no “/api"and it works just fine. I can do that with 8 blinds separately.


With the multiple url I gave in 3 url what you see below in the json file: it does not work.

			"http://192.168.1.7/command?XC_USER=luc.vorstenbos@skynet.be&XC_PASS=LLLLLLLLLL&XC_FNC=doAction&id=04/switch1On",
			"http://192.168.1.7/command?XC_USER=luc.vorstenbos@skynet.be&XC_PASS=LLLLLLLLLL&XC_FNC=doAction&id=03/switch2On",
			"http://192.168.1.7/command?XC_USER=luc.vorstenbos@skynet.be&XC_PASS=LLLLLLLLLL&XC_FNC=doAction&id=01/switch3On”
	
	At the end I tried “/switch1on” with a number, with no number, with and without “/api” I can not get it to work.
	The url ’s are the same as in the single version, exept the end “/switch….” 
	There is something I miss!!! Just stupid me.

Please try again toe explain what I do wrong. I’m just an amateur desparately try to get it work.

Regard,

Luc

**Comment by Supereg** [comment]
Are you sure you are on the latest version? What did you do to update the package?

**Comment by LucLisette** [comment]
Hello Andi,

Indeed, I try single stateless with and without /switch#On, and yes both work.

About installation, I installed (updated) your package with: sudo npm i -g homebridge-http-switch
I did so the first time and now a few days ago with your update did it again like that.
It was rhe only way to get it installed without warnings.
Now it said that 3 file are updated. (I think, not sure)

Regard,

Luc

**Comment by LucLisette** [comment]
Hey Andi,

Wow, it works!!
Can you tell me what went wrong? I’m very curious.
I am a retired teacher electronics with no experiance in programming.
After updating again 1 file had an update.
How many url’s at the same time can I use?

Many thanks and succes whatever you do. My guess is you are a student.

Regards

Luc

**Comment by LucLisette** [comment]
Hello Andi,

Since you updated jour package to version 2 with multiple URL everything works fine.
I like it spacialy because I can use my own language (dutch) in json “name”.
Siri reponds perfect.

You have updated to version 4.xx. Can I do the update without getting into trouble
with config.json or …..

As it works now it is fine but I have to make an accessoirie for every action.
I mean like 	“blind 1 up” = url 1
			“blind 1 down” = url 2
			……..

Would it be possible to make so that when I can say “Blind 1” and it will go up when it was down or down when was up.
I could even stop the blind going further with the same command. Now I have to hurry and say the opposit command to stop the blind to the end.
Much like a mecanical change-over-switch. It would reduce my commands by 1/2.

Hopefully you can see that it could be interesting.

Regards

Luc

**Comment by Supereg** [comment]
Yes, you can update to the latest version without any problems. The version should generally be more stable and robust.
I don't quite understand your problem or what you want to do. Maybe you can clarify it a bit in order to be able to help you.

Sorry for the long response time,
Greets
Andi

**Comment by LucLisette** [comment]
Hello Andi,

When I update do I need to make a new json file? 
Does the timeout appear automatically in existing json?
Or doesn’ t it matter and can I leave my json as it is?

I have no real problem as all is working fine but perhaps it could work nicer.

Example of how my blinds work just now using stateless switch:

	“window 1 open”	window opens till the end unless I say “window 1 close”, then it stops.
	“window 1 close”	window closes till the end unless I say “window 1 open” then it stops.
	
What could be nicer:
	“window 1” window opens unless I say “window 1” again, then it stops. Saying “window 1” again window closes…...

So every time I give the same command the blind does: open, stop, close, open……
	As it is now: every move has its own command.
	Perhapsit could work with only one command. 

	Url should then be:
	url1, url2; url2, url1, url1…..
	up, stop, down, stop, up, stop ……

Resulting in less commands, that is all.

As I write this I don’t think it it wise. When one blind is down and the other up it seems impossible to say “all down” or “all up”????

Regards

Luc

**Comment by Supereg** [comment]
You do not need to change anything in your configuration file.
The `timeout` property does not appear automatically in the file itself, but there is no need to specify it. It will fall back to the default value automatically (which is 1s, like in old version). 

I don't think I can implement this in a practical way. You could potentially create a custom http server which then decides where to forward the http request coming from the switch accessory. But I think controlling this becomes pretty complicated pretty fast.

**Comment by LucLisette** [comment]
Thank you Andi. I leave it just as it is. It 's fine that way.
