### ISSUE TITLE
Ocassional random behaviour

### ISSUE THREAD

**Issue by nchlsgh1** [Supereg/homebridge-http-switch#10]
**Describe the bug**
Occasionally this will hang the remote HTTP server due to not closing connection. On looking at the log I can see that the first few minutes - hours are ok.
1. HomeKit App launched
-All API Status requested 
2. While HomeKit App is still launched
-Toggling a switch to on sends On status to the remote server
-Toggling a switch to off sends Off status to the remote server
Output when ok--
Lights Toggle On
new client
GET /?LightingON HTTP/1.1
host: 192.168.0.130
Connection: close
Lights Toggle Off
new client
GET /?LightingOFF HTTP/1.1
host: 192.168.0.130
Connection: close

The problem arises when the app is still open and http-switch starts requesting Status and then On/Off after every toggle command. Once this occurs, it locks up the remote server.

Output when error starts occuring--
**Lights Toggle On**
new client
GET /?LightingStatus HTTP/1.1
host: 192.168.0.130
Connection: close
new client
GET /?LightingON HTTP/1.1
host: 192.168.0.130
Connection: close

**Lights Toggle Off**
new client
GET /?LightingStatus HTTP/1.1
host: 192.168.0.130
Connection: close
new client
GET /?LightingOFF HTTP/1.1
host: 192.168.0.130
Connection: close

**Expected behavior**
NA

**To Reproduce**
Unable to reproduce on demand

**Version** (output of `npm list -g homebridge homebridge-http-switch`)
 - homebridge:  homebridge@0.4.38
 - homebridge-http-switch: 0.4.12 -> Just updated to 0.4.14

**Configuration**
``
{
			"accessory": "HTTP-SWITCH",
			"name": "Tank Light",

			"switchType": "stateful",

			"httpMethod": "GET",
			"onUrl": "http://192.168.0.130/?LightingON",
			"offUrl": "http://192.168.0.130/?LightingOFF",

			"statusUrl": "http://192.168.0.130/?LightingStatus"
		},
		{
			"accessory": "HTTP-SWITCH",
			"name": "ATO Pump",

			"switchType": "stateful",

			"httpMethod": "GET",
			"onUrl": "http://192.168.0.130/?ATOON",
			"offUrl": "http://192.168.0.130/?ATOOFF",

			"statusUrl": "http://192.168.0.130/?ATOStatus"
		},
		{
			"accessory": "HTTP-SWITCH",
			"name": "Drain Pump",

			"switchType": "stateful",

			"httpMethod": "GET",
			"onUrl": "http://192.168.0.130/?DRAINON",
			"offUrl": "http://192.168.0.130/?DRAINOFF",

			"statusUrl": "http://192.168.0.130/?DrainStatus"
		},
		{
			"accessory": "HTTP-SWITCH",
			"name": "Pump Lock",

			"switchType": "stateful",

			"httpMethod": "GET",
			"onUrl": "http://192.168.0.130/?PUMPLKON",
			"offUrl": "http://192.168.0.130/?PUMPLKOFF",

			"statusUrl": "http://192.168.0.130/?PumpLKStatus"
		}

	],
```

**Additional context**
Happens randomly until a reset of the remote HTTP Server (Arduino Ethernet)

**Comment by nchlsgh1** [comment]
Just occurred again this time with debugger on

Pressing ATO Off in Homeplug generates 2 requests 1 for status first then 1 for actual command
The duplicates are my echo on

new client
GET /?ATOStatus HTTP/1.1
host: 192.168.0.130
Connection: close

Complete String
GET /?ATOStatus HTTP/1.1
host: 192.168.0.130
Connection: close


Normal Closure
new client
GET /?ATOOFF HTTP/1.1
host: 192.168.0.130
Connection: close

Complete String
GET /?ATOOFF HTTP/1.1
host: 192.168.0.130
Connection: close


Normal Closure

Pressing DRAIN On in Homeplug generates 2 requests 1 for status first then 1 for actual command

new client
GET /?DrainStatus HTTP/1.1
host: 192.168.0.130
Connection: close

Complete String
GET /?DrainStatus HTTP/1.1
host: 192.168.0.130
Connection: close


Normal Closure
new client
GET /?DRAINON HTTP/1.1
host: 192.168.0.130
Connection: close

Complete String
GET /?DRAINON HTTP/1.1
host: 192.168.0.130
Connection: close


Normal Closure
new client
GET  /?DrainStatus HTTP/1.1
host: 192.168.0.130
ConnNormal Closure
*At this point the ethernet shield hangs and no longer accepts web commands

**Comment by nchlsgh1** [comment]
Something strange is going on with the Arduino.. I suspect it's the ethernet shield itself once I saturate the connection.. Closing the issue for now

**Comment by nchlsgh1** [comment]
Definitely an issue with my own code for the freezing portion which has now been fixed... but it's interesting to see that on command occasionally I see 2 GET request coming in but not all the time. Would this be due to how HomeKit works where it wants to definitely check the status first before committing to the command (When the app is opened it does a Status GET already)?

On single OFF command
new client
GET /?ATOStatus HTTP/1.1
GET Request Received
Normal Closure

new client
GET /?ATOOFF HTTP/1.1
GET Request Received
Normal Closure




On single ON command
new client
GET /?ATOStatus HTTP/1.1
GET Request Received
Normal Closure

new client
GET /?ATOON HTTP/1.1
GET Request Received
Normal Closure

**Comment by Supereg** [comment]
Seems like your Arduino can't really handle concurrent request.
Cause HomeKit decides which requests it makes. `homebridge-http-switch` does only forward those requests which it gets from a HomeKit controller.
Good lick solving your issue 😃
