### ISSUE TITLE
Boolean with true/false

### ISSUE THREAD

**Issue by 420Dope** [Supereg/homebridge-http-switch#11]
Hello again ;)
nice to see that you are activ and updates your plugin. With [your help](https://github.com/Supereg/homebridge-http-switch/issues/7) , i can controll my Enigma2 receiver with homebridge. Thanks again for that.
At this time, i use only the onUrl and the offUrl. I don´t can use the statusUrl, because the status use boolean function with true and false. The plugin doesn´t know that 0 is false and 1 is true. So the switch in the Home App is always off. It would be nice if you can add these to statusUrl.
But the receiver gives only a status if the receiver is in standby (true) or is not in standby (false).

`<e2powerstate>`
`<e2instandby> true </e2instandby>`
`</e2powerstate>`

So the switch in the Home App was inversely. Maybe you can also add a option which inverts the status and the switch in the Home App shows the right status.

Sorry for my bad english, it is not my first language. I hope you have understand what i want :).
Best regards.

**Comment by 420Dope** [comment]
Sorry i don´t want to bother you.
Other idea, maybe we can determine what the "magic word" is. For example, the device don´t responds with 0/1 or true/false but answers with maybe "activ" or "inactiv". So we can set the "magic word" in the plugin for on and off.
I just got this in my head. So you are more flexible...

**Comment by Supereg** [comment]
This is a feature which is already planned. I though about implementing some sort of configurable regex pattern matching in order to support configuring any sort of complex response.
I let you know when the feature is available :)

**Comment by 420Dope** [comment]
Oh, this is nice to hear.
Thank you very much for your hard work and this great plugin (:

**Comment by Supereg** [comment]
With newly released version v0.5.4 you can specify a custom pattern for the status body using `statusPattern` property. Everything you need to know should be documented in the README.
Reach out if you need help.

**Comment by 420Dope** [comment]
Oh cool, that was fast. Tomorrow i have a little bit time and can test it.
Thank you.
