### ISSUE TITLE
HowTo: Sending JSON via ntfy.sh

### ISSUE THREAD

**Issue by Write** [Supereg/homebridge-http-switch#113]
Here's a working example to send JSON body trough ntfy.sh, as I had much issue to do it.

```
       {
            "accessory": "HTTP-SWITCH",
            "name": "JSONTest",
            "switchType": "stateless",
            "serialNumber": "SW002",
            "timeout": 1000,
            "debug": true,
            "method": "POST",
            "onUrl":
            {
                "url": "https://ntfy.sh/",
                "method": "POST",
                "headers":
                {
                    "Content-Type": "application/json"
                },
                "body":
                {
                    "topic": "your_topic",
                    "title": "🔥  NAS is running hot 🔥",
                    "message": "temperature is over 95",
                    "attach": "https://sflanders.net/wp-content/uploads/2015/11/synology-150x150.png"
                }
            }
        }
```

Remember: As per [ntfy.sh](https://ntfy.sh/docs/publish/#publish-as-json) doc : When sending a JSON notification, it must be sent to the root URL, and the topic in the body under "topic". 

Thanks to https://github.com/Supereg/homebridge-http-switch/issues/103#issuecomment-999190364 / @mbierman's message which helped me a lot.

**Comment by gandalfk7** [comment]
thanks, this helped me a lot!!

**Comment by Supereg** [comment]
I included your example in https://github.com/Supereg/homebridge-http-switch/wiki/Community-supplied-examples
