### ISSUE TITLE
Is this possible with the current release?

### ISSUE THREAD

**Issue by RienduPre** [Supereg/homebridge-http-switch#16]
Hi,

I have a fire place which I can turn of and on with the same http post command (url)
But to turn it of, I have to sent it twice
There is no status url 

So I want a simple switch which sends this command to turn it on
 "http://localhost:8282/hubs/woonkamer/devices/openhaard/commands/power_toggle"

And sends the same url twice to turn off

I cannot use stateful, because I have no status url and I cannot use stateless because for of I have to sent the url twice.

Any help is welcome.

Beste regards,
Rien

**Comment by Supereg** [comment]
Hey,

actually this kind of concept is already on my todo list 😅
Some kind of switchtype „toggle“ using only on and off url.

Maybe I could manage to implement it in the next days. Until then you could create two separate “stateless” switches. One to turn on the device and the second with an array of two urls as “onUrl” to turn it off.

Andi

**Comment by Supereg** [comment]
Just curious, in what time frame does the second request need to arrive, because this is pretty awkward design from the manufacturer.

**Comment by RienduPre** [comment]
It is a fireplace, which uses InfraRed via a HarmonyHub. When the fire place is off it reacts directly on the power toggle IR command. When the fireplace is on the IR receiver goed in some sort of stanby mode. You first hav to sent an IR command to wake the IR system for 10 seconds and you have to send the IR command you want to use within those 10 seconds to execute. 

Is this crearly enough?

**Comment by RienduPre** [comment]
Any news on this ?

**Comment by Supereg** [comment]
So, the first part of this is live as v0.5.8. This versions add the "toggle" switch type. For more information look at the README file. Basically it should allow you to configure one onUrl and an array of offUrls without specifying a statusUrl.
However the current multiple url execution strategy is to execute all urls in parallel for best possible performance. It should probably work beside that however I also wanted to integrate some options which allow you to specify the strategy to use for example execution in series. This will come in the next update. Will notify you about that change.

**Comment by Supereg** [comment]
Okay, found some time in the evening today and implemented the last missing piece.

For your setup to work you need to have a look at the following things:
* `switchType`="toggle"
* `multipleUrlExecutionStrategy`="series"
* Optionally if your http device needs some delay between the requests you can look at the newly implemented [delay urls](https://github.com/Supereg/homebridge-http-switch#the-delay-url)

**Comment by RienduPre** [comment]
Hi,

I used this setup, but it seems it does not use the POST parameter.

This is what I see in the logs

Oct 14 11:33:18 homebridge harmony-api[555]: '[2018-10-14T09:33:18.488Z] - ::ffff:127.0.0.1 - GET /hubs/woonkamer/devices/led-openhaard/command%20power_toggle 404 1.463 ms - 198b'
Oct 14 11:33:18 homebridge homebridge[15631]: [2018-10-14 11:33:18] [Openhaard] Error occurred setting state of switch: HTTP request returned with error code 404

This is my config
{
            "accessory": "HTTP-SWITCH",
            "name": "Openhaard",
            "switchType": "toggle",
            "multipleUrlExecutionStrategy": "series",
            "method": "POST",
            "onUrl": "http://localhost:8282/hubs/woonkamer/devices/led-openhaard/command power_toggle",
            "offUrl": [
                "http://localhost:8282/hubs/woonkamer/devices/led-openhaard/command power_toggle",
                "delay(1000)",
                "http://localhost:8282/hubs/woonkamer/devices/led-openhaard/command power_toggle"
            ]
        }
