### ISSUE TITLE
Not able to get Switch State using statusPattern

### ISSUE THREAD

**Issue by vmhlanga** [Supereg/homebridge-http-switch#17]
Hi there , 

Im currently using this for the Shelly1 Relay and provided is my config for this accessory. Im am not able to get current state of switch in homebridge. I can do everything else switch on and off, just not able to get current state when I exit and or restart HomeApp. I think my string pattern is not correct. When I make the call to the switch it returns 
`{
    "ison": true,
    "has_timer": false
}` meaning the relay is on. 

Can you please confirm below if I am making the right Regex expression to accommodate this response. 

`"accessories": [
        {
          "accessory": "HTTP-SWITCH",
          "name": "Truck Heater",

          "switchType": "stateful",

          "onUrl": {
            "url": "http://localhost/relay/0?turn=on",
            "method": "POST"
          },
          "offUrl": {
            "url": "http://localhost/relay/0?turn=off",
            "method": "POST"
          },
        
          "statusUrl": {
            "url": "http://localhost/relay/0/status",
            "method": "GET"
          },
	"statusPattern": "{\n    \"ison\": true,\n    \"has_timer\":false\n}"
}
]`

**Comment by Supereg** [comment]
The `statusPattern` needs to match every space and also every line break (represented with "\n").
Youre response as mentioned above does not contain line breaks and also does only contain single spaces. In your statusPattern are line breaks followed with tabs/4 spaces. (Probably copied from the example).
A status pattern of 
```json
{
    "statusPattern": "{ \"ison\": true, \"has_timer\": false }"
}
```
should work if your response is exactly as you specified in the issue.
