### ISSUE TITLE
Digest auth support

### ISSUE THREAD

**Issue by northberl1n** [Supereg/homebridge-http-switch#18]
**Describe the bug**
Basic auth is not working

**Expected behavior**
When using the "auth" parameter for your plugin I still get 401 not authorized for each request. I was testing the same setup but with homebridge-http and its working all fine. I would prefer using your plugin though. Could you have a look into that?

**Version** 
 - homebridge: homebridge@0.4.45
 - homebridge-http-switch: homebridge-http-switch@0.5.9

**Configuration**
{
    "accessories": [
        {
          "accessory": "HTTP-SWITCH",
          "name": "Switch",
          "switchType": "stateful",
          "auth": {
               "username": "myUsername",
               "password": "myPassword"
          },         
          "onUrl": "http://localhost/api/switchOn",
          "offUrl": "http://localhost/api/switchOff",
          
          "statusUrl": "http://localhost/api/switchStatus"
        }   
    ]
}

**Comment by Supereg** [comment]
That’s sound weird. I’m looking into this issue.

Could you enable the debug mode and send what exactly the http server returns?
Does it work when you use „http://username:password@example.com“ for each url?

Thanks for the report.

**Comment by northberl1n** [comment]
Hi Andi,

to include user and password into the URL is not working when using a browser to do the request. To give you some context, the web-server is hosted by an IP camera and the request actually a CGI command modifing the motion detection settings.

I started homebridge in DEBUG mode and this is what I see:

`EventedHTTPServer [::ffff:192.168.178.59] HTTP request: /characteristics +2s`
`HAPServer [CC:22:3D:E3:CE:32] HAP Request: PUT /characteristics +1ms`
`Accessory [MyHomebridge] Processing characteristic set: [{"aid":6,"iid":10,"value":1}] +2ms`
`Accessory [MyHomebridge] Setting Characteristic "On" to value 1 +1ms`
`[01/11/2018, 19:40:06] [Switch] Error occurred setting state of switch: HTTP request returned with error code 401`
`Accessory [MyHomebridge] Error setting Characteristic "On" to value 1:  Some or every request returned with an error. See above! +63ms`
`EventedHTTPServer [::ffff:192.168.178.59] HTTP Response is finished +2ms`

Any idea what that characteristic issue could be?!

Thx Ivo

**Comment by Supereg** [comment]
Okay, sorry I probably was a bit unclear. Thanks for your output however the plugin has it‘s own debug mode (i should probably look if I could enable this mode when homebridge is also in debug mode)
You can enable it by setting „debug“=true in the config.json for this accessory.
This mode is useful since it prints the whole body returned by the request. Maybe this could give some more hints.

In the meantime I try to reproduce this problem.

**Comment by northberl1n** [comment]
I added the debug parameter to your plugin, but I don't see any further output on the homebridge console, it would appear within the default homebridge logging, would it?

Am I missing something?

**Comment by Supereg** [comment]
I does not print that much more information. However there should be a additional line about the request body after `[01/11/2018, 19:40:06] [Switch] Error occurred setting state of switch: HTTP request returned with error code 401`

The config should look like this
```json
{
    "accessories": [
        {
          "accessory": "HTTP-SWITCH",
          "name": "Switch",
          
          "switchType": "stateful",
          
          "onUrl": "http://localhost/api/switchOn",
          "offUrl": "http://localhost/api/switchOff",
          
          "statusUrl": "http://localhost/api/switchStatus",

          "debug"=true
        }   
    ]
}
```

**Comment by northberl1n** [comment]
Unfortunately not. That’s all I see despite the debug mode set:
 
![grafik](https://user-images.githubusercontent.com/44677009/47908980-dc724a00-de8e-11e8-8f92-3346e9279429.png)

Full config.json:

![grafik](https://user-images.githubusercontent.com/44677009/47909138-51de1a80-de8f-11e8-9bcc-3336f5a689f8.png)

**Comment by Supereg** [comment]
Okay so I‘m currently analyzing where the issue could be. You said that using a Browser with username and password does fail? However [homebridge-http](https://github.com/rudders/homebridge-http) does work? That’s especially weird since this plugin uses the same underlying framework for http requests. Did you set the „sendimmediately“ in homebridge-http?

Are there maybe any weird or unusual characters in the string? 😅 although this shouldnt be a problem.

I‘m preparing an update which adds a bit more debug output around auth. However this could take till tomorrow as of right now I don’t have access do my computer.

**Comment by Supereg** [comment]
Do you have a machine running some sort of Linux or macOS? If so could you run the following command:
‚curl -sSL -D - example.org -o /dev/null‘
(Replacing example.org with your url)

What this command does is sending a http request and printing the http headers returned from the server. Particularly interesting is the „WWW-Authenticate“ header.

If your not able to run curl (basically if you have windows 😅) that’s also no problem, I try to implement the same debugging method into the plugin itself. Takes some time however.

**Comment by northberl1n** [comment]
It's a Linux ARMV71. 

curl response:

`HTTP/1.1 401 Unauthorized`
`WWW-Authenticate: Digest realm="Login to 3L019D0PAJ00093", qop="auth", nonce="1192344548",opaque="e6f88e9003057a664ca339237e6c8b6c57f2d673"`
`Connection: close`
`CONTENT-LENGTH: 0`


That's the camera documentation regarding the supported authentication methods:

![grafik](https://user-images.githubusercontent.com/44677009/47911258-4857b100-de95-11e8-87c8-6fb94cda0ec0.png)


So somehow homebrige-http is doing something different for its request authorization.

**Comment by Supereg** [comment]
Okay so I think I maybe got some solution.
The think is that you IP camera doesn’t use basic authentication. It uses digest authentication.
The good news the underlying http framework should be able to handle that method. So it shouldn‘t be that much work to support it.

**Comment by northberl1n** [comment]
Let me know if you want me to re-test anything if an update comes available!

**Comment by Supereg** [comment]
I publish v0.5.10 which adds support for digest authentication.
For digest authentication to work you will need to set the property auth.sendImmediately to false in your config. Have a look at the README file for more information.

I decided to set the sendImmediately default to true since for the most people this will result in faster request and less request sent.

**Comment by northberl1n** [comment]
Thanks for the update, unfortunately I cannot confirm its working now.

After I installed v0.5.10 I modified the configuration to:
![grafik](https://user-images.githubusercontent.com/44677009/48188339-da503580-e33d-11e8-8d46-58393a930bfb.png)


I am still getting 401’s, what is also confusing is that I still don’t see any debug output
![grafik](https://user-images.githubusercontent.com/44677009/48188277-b12fa500-e33d-11e8-9185-7559bdf4c081.png)

To make sure none of the other settings/systems changed, I re-tested homebridge-http and its still working. Config:
![grafik](https://user-images.githubusercontent.com/44677009/48188880-0fa95300-e33f-11e8-8b28-c57da6cb8938.png)

Log:
![grafik](https://user-images.githubusercontent.com/44677009/48188586-65313000-e33e-11e8-86b9-b496311c310a.png)

**Comment by Supereg** [comment]
v0.5.11 is live now. Digest authentication works now as expected 😃 
Sorry for the inconvenience.

**Comment by feedericob** [comment]
Hi,
i use this code:

{
    "accessory": "HTTP-SWITCH",
    "name": "Switch",
    "switchType": "stateless",
    "auth": {
        "username": "xxx",
        "password": "xxx",
        "sendImmediately": "false"
    },
    "debug": "true",
    "onUrl": "http://192.168.1.250/cgi-bin/accessControl.cgi?action=openDoor&channel=1&UserID=101&Type=Remote"
}

But in the log i recive this error

[9/29/2023, 5:53:09 PM] [Switch] setStatus() doing http request...
[9/29/2023, 5:53:09 PM] [Switch] Error occurred setting state of switch: HTTP request returned with error code 401
[9/29/2023, 5:53:09 PM] [Switch] Resetting switch to OFF

May you help me?
Best
