### ISSUE TITLE
Feature Request Switch Subtype "Valve"

### ISSUE THREAD

**Issue by desq42** [Supereg/homebridge-http-switch#2]
Hi,

I would like to use "homebridge-http-switch" to switch my valves for watering the garden.
Is it possible to change the device type to "valve"? (iOS11 supports these new "switches", which turn off after a specific time…)

Thx,

desq

**Comment by Supereg** [comment]
This is not possible with this switch, as it is the type/service „switch“. Valves are a completely other type/service which has different characteristics, like setting the duration. As of this you need to write a completely new plugin (if there isn’t already one out there) which identifies as a valve service and has all the required or optional valve characteristics.

**Comment by desq42** [comment]
Okay. Thank you for the explanation.
