### ISSUE TITLE
how to use the custom statusPattern

### ISSUE THREAD

**Issue by iLumen** [Supereg/homebridge-http-switch#20]
Can you please help me ?
I dont know what I am doing wrong...

![code](https://user-images.githubusercontent.com/4661044/48889834-62066b80-ee37-11e8-8966-3835176d5c93.png)

![cmd](https://user-images.githubusercontent.com/4661044/48889894-8f531980-ee37-11e8-859b-8d8f0f009051.PNG)

> [2018-11-22 09:06:42] [shelly2 2] Body of status response is: '{"ison":true,"has_timer":false,"overpower":false,"is_valid":true}'
[2018-11-22 09:06:42] [shelly2 2] Switch is currently OFF

Can you please help me to find the right statusPattern?

**Comment by Supereg** [comment]
I‘m gonna look into it. Please have some patience, since I got very little time at the moment.

**Comment by iLumen** [comment]
Okay, thanks, then I'll wait for an answer from you.

**Comment by Supereg** [comment]
So I tried testing your configuration and couldn't find mistakes. So you get a clear 'works on my machine' 😄 

However I published an update v0.5.13 which prints some more debug information. Would be great if you could update your `homebridge-http-switch` plugin and poste the log output. A snippet from everything printed when the plugin is loaded as well when a status requests is performed would be great.

Maybe you could also double check (with curl or something) if your pattern exactly matches the response from the shelly device. Every space or new line is relevant there.
Also the relevant json property from the response is 'ison' (isn't it?). Do the other properties change in runtime? 

I noticed that this is some sort of Shelly Switch? I ordered some for me some weeks ago, they should get to me hopefully soon. Maybe I could help you more. However they need to arrive first 😅 

Greets

**Comment by iLumen** [comment]
so first I updatet the `homebridge-http-switch` plugin to version `0.5.13`
![version](https://user-images.githubusercontent.com/4661044/49137707-88238400-f2ed-11e8-8a47-571f9e2151ce.PNG)

When I start `homebridge` this is the output I get for `homebridge-http-switch`:
![load1](https://user-images.githubusercontent.com/4661044/49137761-adb08d80-f2ed-11e8-8793-8fa982915923.PNG)
![load2](https://user-images.githubusercontent.com/4661044/49137767-af7a5100-f2ed-11e8-8d2b-b7402d66aa4a.PNG)

as soon as homebridge is started, I open the "home" app on my smartphone, switch on the "shelly" 😅 and get the following output:
![turnon](https://user-images.githubusercontent.com/4661044/49137897-0ed86100-f2ee-11e8-8fec-8e83a4931b81.PNG)

shelly is now turned on...
![shelly_check](https://user-images.githubusercontent.com/4661044/49137907-14ce4200-f2ee-11e8-8c09-e66162e5988f.PNG)
![web](https://user-images.githubusercontent.com/4661044/49138031-6971bd00-f2ee-11e8-8589-c4a43129d43c.PNG)

if I close the "Home" app now and open it again I get the following output
![check](https://user-images.githubusercontent.com/4661044/49137829-e05a8600-f2ed-11e8-8ced-b7476b113f01.PNG)

When I use curl (I hope I'm doing it right) I get the following message...
![curl](https://user-images.githubusercontent.com/4661044/49138071-8c9c6c80-f2ee-11e8-9495-87eb39577b8c.PNG)

That's right. It´s a "shelly2".
Oh, that's great. I hope you get it soon 👍 

Thanks for the great support.
I really appreciate that. 🥇

**Comment by iLumen** [comment]
> Also the relevant json property from the response is 'ison' (isn't it?). Do the other properties change in runtime?

Thats right, "ison" is the relevant property..

![web](https://user-images.githubusercontent.com/4661044/49138400-590e1200-f2ef-11e8-924d-d7ec16f7b5d3.PNG)
![web2](https://user-images.githubusercontent.com/4661044/49138444-7642e080-f2ef-11e8-9044-3ee373364b9d.PNG)

I don't think the other parameters would change that way.
https://shelly-api-docs.shelly.cloud/#shelly-switch-relay-index

![shelly_doc](https://user-images.githubusercontent.com/4661044/49138637-02550800-f2f0-11e8-9b22-d3e00a33457a.PNG)

**Comment by Supereg** [comment]
Okay as I assumed there is probably some sort of character encoding problem in the config. I could be wrong what the exact cause is. Could also be confusion about the config file on your side.
When you look closely into the logs where it prints the statusPattern which is configured you can read: '..."iseon":true....'
So please double check your config, maybe retype the specific part.

**Comment by iLumen** [comment]
That´s it ! 🙈 
Now everything is working 👌 

But why didn't it work with this configuration before ?

> Can you please help me ?
> I dont know what I am doing wrong...
> 
> ![code](https://user-images.githubusercontent.com/4661044/48889834-62066b80-ee37-11e8-8966-3835176d5c93.png)
> 
> ![cmd](https://user-images.githubusercontent.com/4661044/48889894-8f531980-ee37-11e8-859b-8d8f0f009051.PNG)
> 
> > [2018-11-22 09:06:42] [shelly2 2] Body of status response is: '{"ison":true,"has_timer":false,"overpower":false,"is_valid":true}'
> > [2018-11-22 09:06:42] [shelly2 2] Switch is currently OFF
> 
> Can you please help me to find the right statusPattern?


**My config now for the 2 Switches:**
```
 {
            "accessory": "HTTP-SWITCH",
            "name": "shelly2 1",
            "switchType": "stateful",
            "onUrl": {
                "url": "http://192.168.1.207/relay/0?turn=on",
                "method": "POST"
            },
            "offUrl": {
                "url": "http://192.168.1.207/relay/0?turn=off",
                "method": "POST"
            },
            "statusUrl": {
                "url": "http://192.168.1.207/relay/0",
                "method": "GET"
            },
            "statusPattern": "{\"ison\":true,\"has_timer\":false,\"overpower\":false,\"is_valid\":true}"
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "shelly2 2",
            "switchType": "stateful",
            "onUrl": {
                "url": "http://192.168.1.207/relay/1?turn=on",
                "method": "POST"
            },
            "offUrl": {
                "url": "http://192.168.1.207/relay/1?turn=off",
                "method": "POST"
            },
            "statusUrl": {
                "url": "http://192.168.1.207/relay/1",
                "method": "GET"
            },
            "statusPattern": "{\"ison\":true,\"has_timer\":false,\"overpower\":false,\"is_valid\":true}"
        }
```

**Comment by Supereg** [comment]
> But why didn't it work with this configuration before ?

I have absolutely no idea 😅 But happy to hear, that it works now.

A little 'pro' tip, I don't know how well you know regex pattern. But in your case it would be enough to set the statusPattern to `"\"ison\":true"`. This would ensure that the pattern matching is unaffected when the other values of the json changes somehow.
The pattern is matched if the pattern is **contained** in the text you want to test. Otherwise if you want to be sure that the complete response matches your body you can prepend `^` and append `$` to your pattern wich match to the beginning or the end of a string.
Don't know if I explained it well enough, what I mean with that is that the pattern `true` matches the text 'true' as well as 'asdtrue asdkw'. However the pattern `^true$` only matches the first one.

**Comment by cgilis** [comment]
Just for reference: 

This worked for me (Shelly Dimmer):

`{
    "accessory": "HTTP-SWITCH",
    "name": "NAME",
    "switchType": "stateful",
    "onUrl": {
        "url": "http://192.168.X.X/light/0?turn=on",
        "method": "POST"
    },
    "offUrl": {
        "url": "http://192.168.X.X/light/0?turn=off",
        "method": "POST"
    },
    "statusUrl": {
        "url": "http://192.168.X.X/light/0",
        "method": "GET"
    },
    "statusPattern": "\"ison\":true"
}`
