### ISSUE TITLE
LG HomeBot support

### ISSUE THREAD

**Issue by netRunner0** [Supereg/homebridge-http-switch#23]
How can I configure the plugin to get the switch status from this page? I gave the data that is displayed in the browser. Link format ends with /status.txt

There is also a battery charge level here, and it would be nice to see it in Homekit.

The status of the switch must be taken from the parameter JSON_ROBOT_STATE

Thank!

`
JSON_ROBOT_STATE="CHARGING"
JSON_BATTPERC="100"
LGSRV_VERSION="lg.srv, V2.34 compiled 10.01.2016, by BigBadaBoom"
LGSRV_SUMCMD="0"
LGSRV_SUMCMDSEC="0.000000"
LGSRV_NUMHTTP="12"
CPU_IDLE="82.39"
CPU_USER="5.14"
CPU_SYS="12.45"
CPU_NICE="0.00"
JSON_TURBO="false"
JSON_REPEAT="false"
JSON_MODE="SB"
JSON_VERSION="16552"
JSON_NICKNAME="HOMBOT"
CLREC_CURRENTBUMPING="20759"
CLREC_LAST_CLEAN="2018/11/29/20/23/17.252300"`

`

**Comment by Supereg** [comment]
What is the value for JSON_ROBOT_STATE for which the switch should be turned on?

As I unterstand it, when you want to display the battery percentage for an accessory you need to add an additional battery service. This is currently not possible with homebridge-http-switch.

**Comment by Supereg** [comment]
For the setup. You of course need to specify the correct `statusUrl`. And in order for the switch to extract the correct data you need to specify like
```json
{
    "statusPattern": "JSON_ROBOT_STATE=\"CHARGING\""
}
```

This would set the switch's state to true if this string somehow exists in the response from the statusUrl.
Be careful when copying those `\"`, I could be that it won't match the response. If you type it on your own it should work. Some weird character set bug I think. See #20

**Comment by netRunner0** [comment]
Supereg, The fact is that a different url is used for status. I give my example:
` {
            "accessory": "HTTP-SWITCH",
            "name": "LG HomeBot",
            "switchType": "stateful",
            "onUrl": "http://10.0.0.32:6260/json.cgi?%7b%22COMMAND%22:%22CLEAN_START%22%7d",
            "offUrl": "http://10.0.0.32:6260/json.cgi?%7b%22COMMAND%22:%22HOMING%22%7d"
        },`

Status url:

`http://10.0.0.32:6260/status.txt`

**Comment by Supereg** [comment]
What status do you mean exactly. I'm not sure that I understand 100% what you want to achieve.
As you stated you have the following config:
```json
{
	"accessory": "HTTP-SWITCH",
	"name": "LG HomeBot",
	"switchType": "stateful",
	"onUrl": "http://10.0.0.32:6260/json.cgi?%7b%22COMMAND%22:%22CLEAN_START%22%7d",
	"offUrl": "http://10.0.0.32:6260/json.cgi?%7b%22COMMAND%22:%22HOMING%22%7d"
}
```

if want a statusUrl, simply add it
```json
{
	"accessory": "HTTP-SWITCH",
	"name": "LG HomeBot",
	"switchType": "stateful",
	"onUrl": "http://10.0.0.32:6260/json.cgi?%7b%22COMMAND%22:%22CLEAN_START%22%7d",
	"offUrl": "http://10.0.0.32:6260/json.cgi?%7b%22COMMAND%22:%22HOMING%22%7d",
        "statusUrl": "http://10.0.0.32:6260/status.txt"
}
```
and of course the appropriate statusPattern.

Or am I getting something wrong?

**Comment by pbksol** [comment]
I doubt this is the right plugin for this task. It's not really a switch but a robot vacuum cleaner. There are different home bridge plugins available for various vacuum cleaners including support for individual functionaries. There's none for the LG though, but this thing needs it's own plugin.
You can more or less emulate it's bare functionality by using the Vacuum as a switch, but it's still not the right plugin for this task and more of a workaround.
Here's one side effect… If you tell Siri to turn on the lights, every device that is registered as a "lightbulb" will be turned on. That's why there are different characteristics ;-)

**Comment by Supereg** [comment]
> I doubt this is the right plugin for this task. It's not really a switch but a robot vacuum cleaner. There are different home bridge plugins available for various vacuum cleaners including support for individual functionaries. There's none for the LG though, but this thing needs it's own plugin.
> You can more or less emulate it's bare functionality by using the Vacuum as a switch, but it's still not the right plugin for this task and more of a workaround.

I'm not exactly sure what he wants to achieve with the switch plugin, so it isn't so easy to help him 😅
And I also don't know or own a LG HomeBot to know what features could be automated with HomeKit.

**Comment by netRunner0** [comment]
I need to competently read the status of the switch.

The device has 2 links on which it displays the status. What should I register in the config file?

Thank!

**Comment by netRunner0** [comment]
![](https://i106.fastpic.ru/big/2018/1224/bc/_1af1557743a99c8b4096706bf4a6c1bc.png)

**Comment by Supereg** [comment]
> Works!

So no further help required?
