### ISSUE TITLE
Challenges when talking to Python http.server for HTTP POST

### ISSUE THREAD

**Issue by roncoejr** [Supereg/homebridge-http-switch#25]
Greetings,

First let me say thank you for the creation of such a well thought out solution.  I'm certain that my issue is relative to something that I've misunderstood.

I've written a basic server using the Python 3.5 http.server module.  This server is configured to respond to GET and POST requests.  For testing outside of HomeKit I've written a tool in PHP that successfully demonstrates the intended use of the Python based server.  Observing packet captures when the test tools are used reveals that the POST is about 36 bytes in length.

Observing packet captures when attempting to use the homebridge-http-switch reveals that the POST is 0 bytes in length.

I'd be most grateful for your thoughts as to what might be the cause.

Thank you, again.

Packet Capture for http-switch communication:
![screenshot from 2018-12-30 20-42-09](https://user-images.githubusercontent.com/25880798/50553371-7712bd80-0c73-11e9-9be3-1ba1d588acc4.png)

Packet Capture for test Utility:
![screenshot from 2018-12-30 20-44-01](https://user-images.githubusercontent.com/25880798/50553384-a9bcb600-0c73-11e9-93cd-0691457db3ea.png)

Output of the http.server module running my basic Python server:
![screenshot from 2018-12-30 20-44-45](https://user-images.githubusercontent.com/25880798/50553395-d96bbe00-0c73-11e9-93ea-41ea021da3e9.png)

**Comment by roncoejr** [comment]
Forgot to attach an image of the output that I see in HomeBridge:

![image](https://user-images.githubusercontent.com/25880798/50553420-5d25aa80-0c74-11e9-80aa-d9651be17ad5.png)

**Comment by roncoejr** [comment]
Disregard.  I must have been up too late trying to get this one resolved.  Fresh perspective this morning yields progress.

**Comment by Supereg** [comment]
I didn’t had time to get my head behind your problem.
Did you solve your issue? Any further help needed?

**Comment by roncoejr** [comment]
> I didn’t had time to get my head behind your problem.
> Did you solve your issue? Any further help needed?

No worries at all.  I'm making progress.  Though, I wonder: should a UrlObj configured as a post request work, or are we limited to GET requests?
