### ISSUE TITLE
Not supported

### ISSUE THREAD

**Issue by sorriso93** [Supereg/homebridge-http-switch#28]
**Describe the bug**
Starting from 0.5.16, I get a "device not supported" in homekit (the icon of the button is now a house!)

**Expected behavior**

**To Reproduce**
1. homebridge v 0.4.45
2. http-switch v 0.5.16
3. stateful switch with all three url (on, off, status) correctly configured

**Version** (output of `npm list -g homebridge homebridge-http-switch`)
 - homebridge: v 0.4.45
 - homebridge-http-switch:  v 0.5.16

**Configuration**
{
            "accessory": "HTTP-SWITCH",
            "switchType": "stateful",
            "name": "Specchio Bagno Max",
            "onUrl": "http://spbagnomax.maxhome/on",
            "offUrl": "http://spbagnomax.maxhome/off",
            "statusUrl": "http://spbagnomax.maxhome/status"
        },
        {
            "accessory": "HTTP-SWITCH",
            "switchType": "stateful",
            "name": "Specchio Bagno Fede",
            "onUrl": "http://spbagnofede.maxhome/on",
            "offUrl": "http://spbagnofede.maxhome/off",
            "statusUrl": "http://spbagnofede.maxhome/status"
        },

**Additional context**

**Comment by Supereg** [comment]
I'm running v0.5.16 myself and absolutely cannot reproduce that. Sound pretty weird 😅 

What version of iOS are you running?
Are there any log messages of homebridge which could give a clue?
Could you attach a screenshot of the icon in the home app? I'm not exactly sure what you mean by `the icon of the button is now a house`. Also are there any additional hints in the Home App?

**Comment by sorriso93** [comment]
You are right it is weird considering till end of december, before leaving home for vacation, was all ok!
iOs v 12.1.2, as you can see same problem on Osx v 10.14.2

I installed http-switch 0.5.12 and restarted the raspberry with homebridge, same behavior as before... sigh

<img width="908" alt="untitled" src="https://user-images.githubusercontent.com/33072571/50610387-12559e00-0ed3-11e9-9709-7e210602d1a4.png">

**Comment by sorriso93** [comment]
It seems a problem with homekit, from homebridge I can use the accessories with success...
<img width="1274" alt="untitled" src="https://user-images.githubusercontent.com/33072571/50614336-ae39d680-0ee0-11e9-86cf-102f8873e6e3.png">

**Comment by sorriso93** [comment]
Hello just to inform you I recovered and old backup, updated the plugin and it seems all ok now.

**Comment by Supereg** [comment]
Okay great!
