### ISSUE TITLE
Changing the Service of the Accessory

### ISSUE THREAD

**Issue by razer4908** [Supereg/homebridge-http-switch#3]
Hello, 

do you think it is possible to change the Service of the Accessory in the Config ? 
I have a Window Covering / Blinds with simple on/off (on=down - off=up) (no percentage etc.) 
Its my goal to have a adequate symbol in the Apple Home App. 

Greetings 
Dominic

**Comment by Supereg** [comment]
If understand it correctly you want to have a window service to reflect the icon correctly in the Home App? This is a bit complicated since the window service require completely different characteristics (not a simple open/close switch).
I am currently working on a simple window service implementation. The window service requires an target position (percentage, 0-100) and a current position (percentage, 0-100) characteristic. However I could maybe implement a way to support “simpler” windows, which only react to an open or close command.
But this will probably take some time. I keep you updated. 

Greets
Andi

**Comment by razer4908** [comment]
Take your time, thank you for your updates and your interest in this request. 

Dominic

**Comment by Supereg** [comment]
I close this issue and will notify you when my window project is released.

Andi

**Comment by razer4908** [comment]
Thank you

**Comment by pbksol** [comment]
I want to jump in here…

You currently use "this.homebridgeService = new Service.Switch(this.name)" but HomeKit supports a lot more stuff. Yes, you can change the Icon using the App, but it's impossible to make it an outlet and depending on the Service HomeKit offers different icons.

So I do ask you to add the Services
- this.homebridgeService = new Service.Lightbulb(this.name)
- this.homebridgeService = new Service.Outlet(this.name)
and make them selectable by the config.

The Outlet-Service needs two additional parameters for the Power-State, which can be simply it's current State.

The "SwitchType" is already in use… What about "DeviceType"?

This allows the plugin to be used for a much broader variety of HTTP-Switches.

I did extend another project with this, but I don't want to mess too much with other peoples code (which sometimes is called contributing), but you can see these Service-Types in action in https://github.com/pbksol/homebridge-sonoff-basic-espeasy-pbk/blob/master/index.js

**Comment by Supereg** [comment]
@pbksol I though about your idea a little bit. 
What I try to prevent is, that the plugin tries to be too many things at once. Wouldn't it be a better approach to create different plugins for each device. So we have the homebridge-http-switch, an homebridge-http-outlet and (homebridge-http-lightbulb)[https://github.com/Supereg/homebridge-http-lightbulb] (which by the way does already exists, but is awfully documented).
This would prevent homebridge-http-switch getting to bloated. I think the configurations options already get a bit confusing for people who are not so familiar with tech. People who want a simple switch plugin get a simple switch plugin (which though has also some powerful features).

Also we could better support characteristics which are unique to the outlet or lightbulb services (like homebridge-http-lightbulb already does in an very undocumented way 😅).

I would love to hear you opinion about it.

**Comment by DownForce17** [comment]
I like the way you approach the things. Thanks a lot for your updates in the http-switch. It has been my most stable plugin. I would love to see your lightbulb implementation/documentation as I would like a dimmable solution in combination with a http server!

Keep up your good work!

**Comment by pbksol** [comment]
Hi!

> What I try to prevent is, that the plugin tries to be too many things at once. Wouldn't it be a better approach to create different plugins for each device. So we have the homebridge-http-switch, an homebridge-http-outlet and (homebridge-http-lightbulb)[https://github.com/Supereg/homebridge-http-lightbulb] (which by the way does already exists, but is awfully documented).

This whole thing is kind of a double-edged sword. Three plugins might make people think that each of them support almost everything that is supported by HomeKit and beyond. One example… There is no native support for Power-Measurements in the HomeKit App that is part of iOS, but HomeKit itself can transport this information and some apps can show them. Other example… HomeKit supports "On Time" to switch a device off after a specific time (outlet only) if the device supports it. There are devices out there which support this on an http base (you can program ESPEasy Sonoffs to support it, the new Shelly support it, too (/relay/0?turn=on&timer=10) – but that is often very specific and offering this in a completely open way might cause a lot of work and can result in a configuration hell.

The current version of your plugin is the by far most flexible plugin – I played around with all of the ones on npm and they more or less suck.
Especially the RegEx support for the "On" Status is very powerful and makes it very easy to use it with all different kinds of HTTP-Devices.

> This would prevent homebridge-http-switch getting to bloated. I think the configurations options already get a bit confusing for people who are not so familiar with tech. People who want a simple switch plugin get a simple switch plugin (which though has also some powerful features).

Adding the two other services was just a quick an dirty way to show an outlet (yes, I can cobble it together by myself, but that sucks somehow). I would love to see more specific plugins for each Service type.

An outlet plugin that covers all the stuff HomeKit can do. A lightbulb plugin that allows dimmers and RGB sliders and so on (there are not many out there, so I believe this is the least important feature)… That said… A HTTP-Dimmer needs RegEx to filter the returned value (if any) an outlet needs the same for Power, Voltage and so on. That's a lot of work and I tend to not burden other people ;-)

Most parts of these plugins may share the same code as it's not that much difference in the base functionality. That might make things easier but it's still a lot of stuff to maintain.


> Also we could better support characteristics which are unique to the outlet or lightbulb services (like homebridge-http-lightbulb already does in an very undocumented way 😅).

That plugin is a good example for how complex things can become if one tries to keep such a plugin as flexible as possible. In it's current state it accepts status urls for brightness, hue and saturation. But can only parse one value per url. If the device returns (outlets do) these values in one url as a json text, there must be some kind of Regex Filtering (which is currently not implemented).

I did not know that you already had a lightbulb plugin (that can be used for more than just a binary lightbulb). In this case splitting it up and making one for outlets might be the better and more future proof solution.

**Comment by Supereg** [comment]
I already have a basic npm module which has pretty much all necessary things in it for my http devices. I already started to design my existing homebridge-http-* plugins in a way it is easy to add features to all of the at once. However there is always work needed to updated each module to the new version of this base module.
I think it is the best to keep the switch plugin clean and start creating new services. Cause would I add those basic implementations of lightbulb and outlet this would of course attract people who want to use those devices. I would definitely not take long for the first person to ask for full features for lightbulb or outlet. Thus I think best practice is to create individual projects for every service.
However what I definitely want is to streamline the configuration options. In best case you could simply turn a switch into a basic outlet by just changing the plugin used in the config.json.

I currently have not so much time. So I can't really estimate how long this would take me. Maybe I could start bringing the existing lightbulb project on the same level as the switch plugin and add some documentation. So the plugin is actually usable 😅 

I'll keep you up to date if I make any progress.

**Comment by Supereg** [comment]
So part one is finished. I spent some time getting a pretty huge update out for my [homebridge-http-lightbulb](https://github.com/Supereg/homebridge-http-lightbulb) plugin. I ported pretty much any feature found in the switch plugin. Also the configuration of `onUrl`, `offUrl` and `statusUrl` are located at the same spot in order to make it easier to switch between the two plugins.

**Comment by pbksol** [comment]
Thanks for the info. I'll check it out next week (I hope – limited on time currently) – but only the switching part… Don't have any HTTP-Dimmers around. There will be some RGBW-stuff in two months or so…
I'm one of the Plug-Guys… But you already know.

Thanks for the effort to bringt the lightbulb plugin on par with the switch. I will post anything regarding it in the Issues section over there…

**Comment by Supereg** [comment]
My outlet plugin `homebridge-http-outlet` is now also live 😃 
https://github.com/Supereg/homebridge-http-outlet
