### ISSUE TITLE
Mqtt config 

### ISSUE THREAD

**Issue by Luftloch80** [Supereg/homebridge-http-switch#33]
Hi is this config right for mqtt or how does it have to Look. Got. noch reaction when topic Is sent. 

mosquitto_pub -h localhost -t 'siedle/cmnd' -m ring_E_D

  {
            "accessory": "HTTP-SWITCH",
            "name": "Türgong",
            "switchType": "toggle",
            "timeout": 1000,
            "debug": true,
            "onUrl": "http://192.168.0.50:5005/clipall/fury.mp3/5",
               "offUrl": "http://192.168.0.50:5005/clipall/fury.mp3/5",
            "mqtt":{
            "host": "192.168.0.50",
            "subscriptions": [
    {
      "topic": "siedle/cmnd",
      "messagePattern": "ring_E_D",
      "characteristic": "On"
    }
  ]

        }}
Says ring_E_D has wrong characteristic
Why Not working with stateless Switch Need it for my doorbell

**Comment by Supereg** [comment]
I tested your provided configuration (as it is right now) and everything works expected.
Could you ensure that the configuration is as mentioned above and the plugin is actually connected to the MQTT broker.
Also are you running the latest version of the plugin (please proved the version number).

> Says ring_E_D has wrong characteristic
You could exactly copy the log message?

Also it could be helpful if you turn on the debug mode of the plugin and paste the additional log output.

**Comment by Luftloch80** [comment]
Thx for quick reply 
[Türgong] MQTT updating characteristic On to true
When publishing topic it sets the switch to true
Also in Home App it Switches on, but it does Not Play the sound. When Pressing the Switch manually it PlayS Sound immediately
Is it possible to make mqtt with stateless switch?

**Comment by Luftloch80** [comment]
I read that it only Sets the State of the Switch. 
Is ist possible to implement that it also sent http command for on State ?

**Comment by Supereg** [comment]
As you found out yourself the MQTT functionality is not intended to do that. And of the plugin standpoint this feature doesn't really make sense to implement.

Did you search for any external modules/software packages which try to bridge mqtt with http? A other solution could be if you create a second switch which gets notified via mqtt and then create an automation inside HomeKit that turns the actual switch on when the second switch gets turned on.
