### ISSUE TITLE
Group switch’s 

### ISSUE THREAD

**Issue by finalhawk90** [Supereg/homebridge-http-switch#45]
Could you please add a feature to group accessories under 1 accessory?
Thanks

**Comment by Supereg** [comment]
I don't know if I'm gonna implement that, as I think the config is already crowded enough and would just introduce much more complication 🤔

**Comment by Final-Hawk** [comment]
Yes it may add more complication, but it would be a great feature if you could implement it!
(had to create another account so this is the person who first put the issue/feature request out)

**Comment by Supereg** [comment]
Honestly, I won‘t see it happening anytime soon. If I decide to add something like that, I will notify you, but currently I really don’t feel like introducing more clutter to the configuration.

**Comment by aebgit** [comment]
I see a great benefit in a grouping of switches (like provided by hk door-locks or cameras) too. I have a lot of single switches for my home-cinema that really clutter my living-room. Having a way to organize them would be really great.
