### ISSUE TITLE
Group switch’s

### ISSUE THREAD

**Issue by Final-Hawk** [Supereg/homebridge-http-switch#49]
Could you please add a feature to group accessories under 1 accessory? I saw the other one and I don’t care if the config is crowded
Thanks

**Comment by Supereg** [comment]
You might not care, but others especially beginners do welcome a less crowded documentation. Also this Plugin was never designed to support something like that. That would mean a major rework to keep it clean. And simply, I currently don’t have the resources to invest that much time for a feature which isn’t that important.
All this reasons make to currently say: no!

But PRs, which implement that while maintaining a clean code base, keeping backwards compatibility and somehow handle mixture of configuration well.
