### ISSUE TITLE
Individual Serialnumber

### ISSUE THREAD

**Issue by RainhardPosch** [Supereg/homebridge-http-switch#55]
Hello,

is it possible to add a parameter/value to set individual serial numbers to each switch?
Because i.e. the EVE app has troubles with devices having all the same serial number.

edit:
I have tested it by edit line number 305 in index.js and it works now in EVE app:
.setCharacteristic(Characteristic.SerialNumber, this.name)

But i think to assign an individual serial number would be the nicer way. :)

Thanks

**Comment by mbierman** [comment]
Maybe I'm not following what you are getting at. It seems each named switch is be treated separately. Just give it a different name.

**Comment by RainhardPosch** [comment]
in apple home everything works as expected. but when you use "eve app" (i like the interface much more), the switches are identified by serial number. so if you want to add one switch to your favourites, every switch with the same serial number (in this case "SW01") will be added abd you're nit able to select only one. in this case it would be nice if it's possible to set the serial number via config.

hope you can understand what i mean. :)

**Comment by Supereg** [comment]
Are you running the latest version of the Eve App? Cause I remember that they did fix that issue?

**Comment by RainhardPosch** [comment]
yes, version 4.2.2 (5 days old)

**Comment by mbierman** [comment]
Strange I’m not having that problem.

**Comment by mbierman** [comment]
Works o.k. for me in Eve. What problem are you seeing?

**Comment by RainhardPosch** [comment]
Sorry for my late answer, i have tested different settings and always got the same result.
When using standard serial number "SW01" for all devices (like in the original code) i can not add only one switch to my favourites (see my attached pictures). I tried to reset my homebridge and readd all HTTP-SWITCHES again, same result. After edit the code (like in my post before) it is possible and works fine.

![01](https://user-images.githubusercontent.com/55686396/82308507-2f084e00-99c2-11ea-9c83-416b4fe4312a.PNG)    ![02](https://user-images.githubusercontent.com/55686396/82308515-316aa800-99c2-11ea-801d-bf45c45c5aad.PNG)    ![03](https://user-images.githubusercontent.com/55686396/82308523-33346b80-99c2-11ea-874e-a78a6fca70f8.PNG)

**Comment by mbierman** [comment]
@RainhardPosch  Does the switch serial number matter?  If I duplicate a switch, I see both in Eve and they work. I haven't tried setting up to see if they properly control separate things though.

**Comment by RainhardPosch** [comment]
it seems that the serial number only matters in the favourites tab.
when switches have the same serial number it is not possible to add a single one but the operational function is given (i can trigger each switch separatly).

in the rooms tab instead the switches are separated correctly.

**Comment by Supereg** [comment]
A new `serialNumber` property was added to v0.5.31 in order to define custom serial numbers.
Sorry for the delay.
