### ISSUE TITLE
Is it possible to send XML Post Request

### ISSUE THREAD

**Issue by samma0815** [Supereg/homebridge-http-switch#63]
Hi,
I use this plugin to send HTTP GET and POST requests in JSON Format to a Yamaha RX-A880 AV Receiver. However some commands require to send an XML request as post, like this one:

<YAMAHA_AV rsp="GET" RC="0">
<System>
<Speaker_Preout>
<Pattern_1>
<Config>
<Front_Presence>
<Type>None</Type>
<Cross_Over>80 Hz</Cross_Over>
</Front_Presence>
</Config>
</Pattern_1>
</Speaker_Preout>
</System>
</YAMAHA_AV>

Is it possible to send that XML request via this plugin? If yes, how would the config look like since I already tried escaping the quotes or use single quotes. However it didn't work me.

**Comment by Supereg** [comment]
Well you can just put it in as a string in the `body` property.
double quotes MUST be escaped using back slash (as double quotes are used in json to mark a string).
Additionally line breaks are not supported by json. Instead you need to replace them by `\n`

So something like the following should work:

```json
{
  "body": "<YAMAHA_AV rsp=\"GET\" RC=\"0\">\n\n<Speaker_Preout>\n<Pattern_1>\n\n<Front_Presence>\nNone\n<Cross_Over>80 Hz</Cross_Over>\n</Front_Presence>\n\n</Pattern_1>\n</Speaker_Preout>\n\n</YAMAHA_AV>"
}
```

**Comment by samma0815** [comment]
Sorry for my late response and thanks so much for your help. I am going to try it out soon.

**Comment by samma0815** [comment]
Works like charm!

 {
            "accessory": "HTTP-SWITCH",
            "name": "AVR Speaker Large",
            "switchType": "toggle",
            "onUrl": {
                "url": "http://192.168.0.28/YamahaRemoteControl/ctrl",
                "method": "POST",
                "body": "<YAMAHA_AV cmd=\"PUT\"><System><Speaker_Preout><Pattern_1><Config><Front><Type>Large</Type></Front></Config></Pattern_1></Speaker_Preout></System></YAMAHA_AV>"
            },
            "offUrl": {
                "url": "http://192.168.0.28/YamahaRemoteControl/ctrl",
                "method": "POST",
                "body": "<YAMAHA_AV cmd=\"PUT\"><System><Speaker_Preout><Pattern_1><Config><Front><Type>Small</Type></Front></Config></Pattern_1></Speaker_Preout></System></YAMAHA_AV>"
            }
        },
