### ISSUE TITLE
serialNumber does not work in Eve

### ISSUE THREAD

**Issue by mbierman** [Supereg/homebridge-http-switch#64]
**Describe the bug**
I set `serialNumber`. It does show up in in Home but it does not show up in Eve.

**Expected behavior**
I would expect the serial number to appear in both apps. 

**To Reproduce**
1. Edit config.json as shown

        {
            "accessory": "HTTP-SWITCH",
            "name": "Arming error",
            "switchType": "stateless",
            "serialNumber": "SW003",
            "timeout": 1000,
            "onUrl": "https://maker.ifttt.com/t...",
            "method": "POST",
            "debug": false
        },

2. Restarthomebridge
3. Check Eve
4. Check Home

**Version** (output of `npm list -g homebridge homebridge-http-switch`)
 - homebridge: 1.1.1
 - homebridge-http-switch: v0.5.31

**Configuration**
```json
....
```

**Additional context**

**Comment by Supereg** [comment]
> I set serialNumber. It does show up in in Home but it does not show up in Eve.

If it shows up in the Home App it is properly save in the HomeKit database. See no Issue in the plugin?
What does it show in the Eve App?

**Comment by mbierman** [comment]
Eve shows the default serial number as if it isn't set at all `SW01` while Home shows what I set above, `SW003`.

I don't see a discrepancy between serial numbers for other accessories.

**Comment by Supereg** [comment]
Well as I said, if Home App displayes it correctly then HomeKit received it correctly and there is nothing we can do about it.
Would assume, as Eve seems to assume that serial numbers never change, that they never update it.
