### ISSUE TITLE
undefined null?

### ISSUE THREAD

**Issue by MatGriffin** [Supereg/homebridge-http-switch#70]
**Describe the bug**
Not really a bug just a quick question

**Expected behaviour**
I use http-switch to control my Enigma2 based satellite box as channels can be changed by http calls. I expose the item as a device in Alexa so I can say "Alexa turn on BBC One".

I notice that I always get the in the Homebridge log `undefined null `just interested what the `undefined null` means.
[10/6/2020, 08:24:29] [Alexa] PowerController TurnOff 0E:7D:D3:49:10:DE undefined null
[10/6/2020, 08:24:34] [Alexa] PowerController TurnOn 0E:7D:D3:49:10:DE undefined null

**Comment by Supereg** [comment]
The provided log messages are not caused by the http-switch plugin.
