### ISSUE TITLE
New Stateless Switch Icon

### ISSUE THREAD

**Issue by Jafalex** [Supereg/homebridge-http-switch#74]
Hi there,
Any chance you can please add the new stateless switch icon?
More here: https://github.com/oznu/homebridge-config-ui-x/pull/951
And here: https://github.com/oznu/homebridge-config-ui-x/releases/tag/4.33.0
Thanks!

**Comment by Supereg** [comment]
This plugin doesn’t expose a StatelessProgrammableSwitch nor a StatefulProgrammableSwitch.
This is a regular switch.
