### ISSUE TITLE
Add new slider switch type

### ISSUE THREAD

**Issue by mrfatboy** [Supereg/homebridge-http-switch#77]
This is a fantastic plugin.  Thanks for all your hard work.

I would like to request a new slider switch type.  This would be a combination of a toggle switch and a yet to be implemented slider/dimmer control.

Short presses would toggle the switch ON & OFF.  Long press would open up a slider control much like a dimmer switch.  The position of the dimmer would call a request object out of user specified list.  The list of request objects would have the same schemas that this plugin uses.  

Example uses include:
-Turning ON/OFF stereo with volume control
-Turning ON/OFF fan with speed control
-Light dimmer switch
-etc.

Another developer has already something similar but it's not 100%.  He has the slider part implemented but not the ON/OFF part. I have contacted him and it is not a high priority for him.  Also, this plugins request object schema is much more versatile.

https://github.com/datMaffin/homebridge-http-slider/blob/request_objects/README.md

Thank you.  Keep up the good work!

**Comment by Supereg** [comment]
Hm I'm not sure if I want to add that feature. At this point I feel like the http switch plugin is already pretty bloated and far away from simple. I think this will only further complicate the configuration.
Also what you want is really a completely different server (like a lightbulb for example). Maybe you just want to look at my http lightbulb plugin if that fits your needs 🤔
