### ISSUE TITLE
Migration to TrueScript?

### ISSUE THREAD

**Issue by mabiste** [Supereg/homebridge-http-switch#79]
Hey @Supereg,

I would like to implement further plug-ins as this http-switch plug-in, using your http-notification server. For example, dimmable light bulb.

I've created my first own plug-in based on the example plug-ins from homebridge developer sites. But the examples all are written in TrueScipt, which I can handle. It would be very helpfull for me, if I had a TruScript based example of a plug-in using your http-notification server plug-in.

Thank you
Marco

**Comment by Supereg** [comment]
*TypeScript

Typescript is nothing else than JavaScript with typing ([see](https://en.wikipedia.org/wiki/TypeScript)). Depending on the Typescript "compiler" (its rather a "transpiler") every javascript code is also Typescript code (rather bad typescript code as the javascript code obviously is missing type information and there is some fancy language features with typescript you can easily use).

I'm sorry at the moment I can't provide you with any TypeScript examples.

**Comment by mabiste** [comment]
OK, thank you...!
