### ISSUE TITLE
Release 0.5.32 is broken!

### ISSUE THREAD

**Issue by aebgit** [Supereg/homebridge-http-switch#80]
Release [0.5.32](https://github.com/Supereg/homebridge-http-switch/releases/tag/v0.5.32) seems to be broken. I installed the update and Homebridge was unable to start and threw `#Error: The requested accessory 'HTTP-SWITCH' was not registered by any plugin.`

Returned to 0.5.31 and everything was OK again. `sudo npm install -g homebridge-http-switch@0.5.31`

Regards
Andreas

**Comment by Supereg** [comment]
Thanks for the quick heads up. Just pulled the update for now and try to investigate the issue later. Sorry for the inconvenience.

**Comment by Supereg** [comment]
Alright, I had some time to analyze what is going wrong. I couldn't find any issues why the plugin wouldn't register itself.
Were there any other errors shown when homebridge was starting up?
Was the update complete when homebridge was starting up? Did the update to 0.5.32 successfully complete?

**Comment by lukenukemmp3** [comment]
The Homemanager displays an update for the release 0.5.31. The update runs without any problem and completes succesfully, but then the version is not 0.5.32 but still 0.5.31.

**Comment by Final-Hawk** [comment]
Same Issue, it just updated though. please revoke it again
