### ISSUE TITLE
Service type

### ISSUE THREAD

**Issue by steaming** [Supereg/homebridge-http-switch#9]
Hi Supereg,

Your plugin so awesome.
But i would like to recommend some feature is Service type Ex. Lamp, Light (like a old plugin) because i use you plugin with light.  

Thank.

**Comment by Supereg** [comment]
You probably want the switch to be displayed as a light in the Home App?
Then you can go to the details/settings tab of the accessory in the Home App and change the „Type“ to „Light“.

**Comment by Supereg** [comment]
![img_0284](https://user-images.githubusercontent.com/9783857/44633304-e1e07f00-a989-11e8-9b6c-1c5e63c62b43.jpg)
