### ISSUE TITLE
Unable to determine plugin type

### ISSUE THREAD

**Issue by mikl10** [Supereg/homebridge-http-switch#93]
my homebridge server hoobs 3.3.5 doesn't load config.json because I have that issue with the plugin :
30/06/2021, 19:25:01 Unexpected token ':'
30/06/2021, 19:25:01 Unable to determine plugin type for "homebridge-http-switch"

When I delete all part with http-switch declaration that work.
{
            "accessory": "HTTP-SWITCH",
            "name": "Portail",
            "switchType": "stateless",
            "timeout": 1000,
            "onUrl": "http://192.168.10.20/control?cmd=Pulse,5,1,500",
            "plugin_map": {
                "plugin_name": "homebridge-http-switch",
                "index": 0
            }

Can you help me to resove that please?

**Comment by mbierman** [comment]
You are missing a "}"

```
{
	"accessory": "HTTP-SWITCH",
	"name": "Portail",
	"switchType": "stateless",
	"timeout": 1000,
	"onUrl": "http://192.168.10.20/control?cmd=Pulse,5,1,500",
	"plugin_map": {
		"plugin_name": "homebridge-http-switch",
		"index": 0
	}
}
```

**Comment by mikl10** [comment]
it is a miss with my copy/paste, in my config file it is present

**Comment by mbierman** [comment]
Can you provide the entire config file?

**Comment by mikl10** [comment]
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYMN3E",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "fr",
        "temp_units": "celsius",
        "country_code": "FR",
        "postal_code": "10150"
    },
    "bridge": {
        "name": "MyHome",
        "port": 51826,
        "pin": "031-45-154",
        "username": "EC:4A:2B:88:4D:62"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "HTTP-SWITCH",
            "name": "Portail",
            "switchType": "stateless",
            "timeout": 1000,
            "onUrl": "http://192.168.10.20/control?cmd=Pulse,5,1,500",
            "plugin_map": {
                "plugin_name": "homebridge-http-switch",
                "index": 0
            }
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "Portail Pieton",
            "switchType": "stateless",
            "timeout": 1000,
            "onUrl": "http://192.168.10.20/control?cmd=Pulse,4,0,500",
            "plugin_map": {
                "plugin_name": "homebridge-http-switch",
                "index": 0
            }
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "Notif Depart",
            "switchType": "stateless",
            "timeout": 1000,
            "onUrl": "https://192.168.10.10:5001/webapi/entry.cgi?api=SYNO.Chat.External&method=incoming&version=2&token=%22eV1PWdLWpHcXXVNPL8QVyM8p7js02cdkFFUtCOIiHNuzXbDIouy9GR56DXJ2820q%22&payload={%22text%22:%22@mikl%20Notif%20Depart%22}",
            "plugin_map": {
                "plugin_name": "homebridge-http-switch",
                "index": 0
            }
        },
        {
            "accessory": "GarageCommand",
            "name": "Garage",
            "open": "python /home/hoobs/scripts/CmdPortail.py2",
            "close": "python /home/hoobs/scripts/CmdPortail.py2",
            "state": "python /home/hoobs/scripts/EtatPortail.py2",
            "status_update_delay": 15,
            "poll_state_delay": 20,
            "plugin_map": {
                "plugin_name": "homebridge-garagedoor-command",
                "index": 0
            }
        },
        {
            "accessory": "DelaySwitch",
            "name": "DelaySwitch",
            "disableSensor": false,
            "delay": 5000,
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            },
            "startOnReboot": false
        },
        {
            "accessory": "DelaySwitch",
            "name": "DelayGarage",
            "disableSensor": true,
            "delay": 600000,
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            },
            "startOnReboot": false
        },
        {
            "accessory": "DelaySwitch",
            "name": "TimerChambreLeana",
            "disableSensor": true,
            "delay": 1800000,
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            },
            "startOnReboot": false
        },
        {
            "accessory": "DelaySwitch",
            "name": "TimerChambreClea",
            "disableSensor": true,
            "delay": 1800000,
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            },
            "startOnReboot": false
        },
        {
            "accessory": "DelaySwitch",
            "name": "TimerEntree",
            "disableSensor": true,
            "delay": 600000,
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            },
            "startOnReboot": false
        }
    ],
    "platforms": [
        {
            "platform": "HttpWebHooks",
            "webhook_port": "51830",
            "cache_directory": "/home/hoobs/storage",
            "sensors": [
                {
                    "id": "sensor",
                    "name": "sonnette",
                    "type": "motion",
                    "autoRelease": true
                },
                {
                    "id": "sensor2",
                    "name": "Portail_Info",
                    "type": "contact",
                    "autoRelease": false
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-http-webhooks"
            }
        },
        {
            "platform": "ProgrammableHTTPSwitch",
            "plugin_map": {
                "plugin_name": "homebridge-programmable-http-switch"
            }
        }
    ]
}

**Comment by mikl10** [comment]
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYMN3E",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "fr",
        "temp_units": "celsius",
        "country_code": "FR",
        "postal_code": "10150"
    },
    "bridge": {
        "name": "MyHome",
        "port": 51826,
        "pin": "031-45-154",
        "username": "EC:4A:2B:88:4D:62"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "HTTP-SWITCH",
            "name": "Portail",
            "switchType": "stateless",
            "timeout": 1000,
            "onUrl": "http://192.168.10.20/control?cmd=Pulse,5,1,500",
            "plugin_map": {
                "plugin_name": "homebridge-http-switch",
                "index": 0
            }
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "Portail Pieton",
            "switchType": "stateless",
            "timeout": 1000,
            "onUrl": "http://192.168.10.20/control?cmd=Pulse,4,0,500",
            "plugin_map": {
                "plugin_name": "homebridge-http-switch",
                "index": 0
            }
        },
        
        {
            "accessory": "DelaySwitch",
            "name": "DelaySwitch",
            "disableSensor": false,
            "delay": 5000,
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            },
            "startOnReboot": false
        },
        {
            "accessory": "DelaySwitch",
            "name": "DelayGarage",
            "disableSensor": true,
            "delay": 600000,
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            },
            "startOnReboot": false
        },
        {
            "accessory": "DelaySwitch",
            "name": "TimerChambreLeana",
            "disableSensor": true,
            "delay": 1800000,
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            },
            "startOnReboot": false
        },
        {
            "accessory": "DelaySwitch",
            "name": "TimerChambreClea",
            "disableSensor": true,
            "delay": 1800000,
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            },
            "startOnReboot": false
        },
        {
            "accessory": "DelaySwitch",
            "name": "TimerEntree",
            "disableSensor": true,
            "delay": 600000,
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            },
            "startOnReboot": false
        }
    ],
    "platforms": [
        {
            "platform": "HttpWebHooks",
            "webhook_port": "51830",
            "cache_directory": "/home/hoobs/storage",
            "sensors": [
                {
                    "id": "sensor",
                    "name": "sonnette",
                    "type": "motion",
                    "autoRelease": true
                },
                {
                    "id": "sensor2",
                    "name": "Portail_Info",
                    "type": "contact",
                    "autoRelease": false
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-http-webhooks"
            }
        },
        {
            "platform": "ProgrammableHTTPSwitch",
            "plugin_map": {
                "plugin_name": "homebridge-programmable-http-switch"
            }
        }
    ]
}

**Comment by mikl10** [comment]
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYMN3E",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "fr",
        "temp_units": "celsius",
        "country_code": "FR",
        "postal_code": "10150"
    },
    "bridge": {
        "name": "MyHome",
        "port": 51826,
        "pin": "031-45-154",
        "username": "EC:4A:2B:88:4D:62"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "HTTP-SWITCH",
            "name": "Portail",
            "switchType": "stateless",
            "timeout": 1000,
            "onUrl": "http://192.168.10.20/control?cmd=Pulse,5,1,500",
            "plugin_map": {
                "plugin_name": "homebridge-http-switch",
                "index": 0
            }
        },
        {
            "accessory": "HTTP-SWITCH",
            "name": "Portail Pieton",
            "switchType": "stateless",
            "timeout": 1000,
            "onUrl": "http://192.168.10.20/control?cmd=Pulse,4,0,500",
            "plugin_map": {
                "plugin_name": "homebridge-http-switch",
                "index": 0
            }
        },
        
        {
            "accessory": "DelaySwitch",
            "name": "DelaySwitch",
            "disableSensor": false,
            "delay": 5000,
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            },
            "startOnReboot": false
        },
        {
            "accessory": "DelaySwitch",
            "name": "DelayGarage",
            "disableSensor": true,
            "delay": 600000,
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            },
            "startOnReboot": false
        },
        {
            "accessory": "DelaySwitch",
            "name": "TimerChambreLeana",
            "disableSensor": true,
            "delay": 1800000,
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            },
            "startOnReboot": false
        },
        {
            "accessory": "DelaySwitch",
            "name": "TimerChambreClea",
            "disableSensor": true,
            "delay": 1800000,
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            },
            "startOnReboot": false
        },
        {
            "accessory": "DelaySwitch",
            "name": "TimerEntree",
            "disableSensor": true,
            "delay": 600000,
            "plugin_map": {
                "plugin_name": "homebridge-delay-switch",
                "index": 0
            },
            "startOnReboot": false
        }
    ],
    "platforms": [
        {
            "platform": "HttpWebHooks",
            "webhook_port": "51830",
            "cache_directory": "/home/hoobs/storage",
            "sensors": [
                {
                    "id": "sensor",
                    "name": "sonnette",
                    "type": "motion",
                    "autoRelease": true
                },
                {
                    "id": "sensor2",
                    "name": "Portail_Info",
                    "type": "contact",
                    "autoRelease": false
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-http-webhooks"
            }
        },
        {
            "platform": "ProgrammableHTTPSwitch",
            "plugin_map": {
                "plugin_name": "homebridge-programmable-http-switch"
            }
        }
    ]
}

**Comment by mikl10** [comment]
> Can you provide the entire config file?
> 
> Also, I’m not familiar with "plugin_map". I don’t see it in the documentation. Can you provide a link to where you got that from?


"plugin_map" it was automatically insert in my backup create with hoobs.

**Comment by mbierman** [comment]
So I use homebridge, not hoobs. I can't find any reference to "plugin_map" anywhere. Have you tried removing all of the instances of it and restarting?

**Comment by mikl10** [comment]
Yes if I remove all declaration "HTTP-SWITCH" it work

**Comment by mbierman** [comment]
Any other recent changes? Update to Hoobs ?  Sorry I don't have a better answer for you.

**Comment by mikl10** [comment]
nop
this week-end I will try to restart all from 0, format SD card and reinstall all plugin. We'll see

**Comment by Supereg** [comment]
Please contact HOOBS support for issues with hoobs. This plugin only supports homebridge and homebridge-ui.
