### ISSUE TITLE
Configuration for Sonoff Switch with homekit firmware

### ISSUE THREAD

**Issue by FabioMC** [Supereg/homebridge-http-switch#94]
I have 3 Sonoff switches with homekit firmware installed, so I was not supossed to use any homebridge setup to control them but I like to centralize all the devices on homebridge installation because I can control all equipments in any non apple devices as well. I can control the sonoff switch by http access and the plugin works well but the status of the switch do not change. Below is an example of one of the Sonoff configuration. Clicking the accessory it goes on and off according I press the button but its status is always off. What am I missing into the plugin configuration?

Note: It only works with swichType: toggle. Stateful always gives me a message informing invalid header token.

            "accessory": "HTTP-SWITCH",
            "name": "Ventilador",
            "switchType": "toggle",
            "onUrl": "http://192.168.15.81/toggle",
            "offUrl": "http://192.168.15.81/toggle"

Thanks

**Comment by remussamoila** [comment]
very funny, indeed
My toogle attempt throws to me a nice error: HPE_INVALID_HEADER_TOKEN
that may be due to new node.js validation
It seems that something is fishy in sonoff page.
