### ISSUE TITLE
Hikvision (DS-KD8003) Door lock trigger

### ISSUE THREAD

**Issue by ayghazali** [Supereg/homebridge-http-switch#98]
Can someone add the function of open door/relay for hikvision doorbells?

I found this [home assistant thread](https://community.home-assistant.io/t/ds-kd8003-ds-kv8113-ds-kv8213-ds-kv6113-ds-kv8413-and-integration-hikvision-hikconnect-video-intercom-doorbell/238535) discussing this and they had this command for open door

To open an electrical door (relay 1 or 2)
curl -i --digest -u admin:xxx -X PUT -d 'open' http://192.168.0.xx/ISAPI/AccessControl/RemoteControl/door/1

Not sure if this can be implemented into this plug-in or any other plugin.

Apologies for the noob question, I'm not a coder, so I don't know how these things work exactly

**Comment by ferdinandhodl** [comment]
send an html string as
`curl -i --digest -u admin:xxx -X PUT -d '<RemoteControlDoor><cmd>open</cmd></RemoteControlDoor>' https://192.168.0.xx/ISAPI/AccessControl/RemoteControl/door/1`

event commands
- open
- close
- alwaysOpen
- alwaysClose
